### ISSUE TITLE
Checklist for 1.0 Beta

### ISSUE THREAD

**Issue by alexjraymond** [alexjraymond/DuelingBookEnhanced#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to use & customize hotkeys, toggle night mode, and various other QoL updates to DuelingBook!

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

- [x] Night Mode
     - [x] [resets when extension popup opens](https://imgur.com/wzwEdD2)
     - [x] [Profile viewing inconsistent](https://imgur.com/zf0wBiL)
- [x] Ensure all cases of sending to graveyard and special summoning work
- [x] Ensure user settings persistency
- [x] Front End
     - [x] Redesign popup with tailwind
     - [x] Ensure fullOptions should be fully click-through-able
     - [x] Ensure proper responsiveness on fullOptions "DBE" text 
     - [x] Add `Known Issues and Upcoming Features` section in fullOptions
- [x] Update the ReadMe 
- [x] Set up BuyMeACoffee account
- [x] Set up disable/enable DBE function
- [x] Finish Discord
- [ ] Create YouTube demonstration video
- [ ] Add LP add/subtract feature

### 🧑‍⚕️ Clean Up Tasks

- [x] Remove all commented code and console logs

### 🧑‍⚕️ Stretch Goals

- [ ] Enable hotkey customization
- [ ] Chain Link declaration popup window
- [ ] Make logic to check if a card was just activated
- [ ] Make the "Normal Summon" hotkey also type "ns" in chat
- [ ] Add "Pot of Prosperity" mill functionality of either 3, or 6, it does mill off the deck, and types "3" or "6" in chat. Maybe use a droplist so users can choose mill amount
- [ ] Add a 'GG' hotkey
