### ISSUE TITLE
Incorporate the NPM package webpack-extension-reloader 

### ISSUE THREAD

**Issue by joseph-w-valdez** [alexjraymond/DuelingBookEnhanced#3]
### Description:
Integrate the "webpack-extension-reloader" npm package into our extension project to enable automatic reloading during development.

### Tasks:
- [ ] Install the "webpack-extension-reloader" npm package using `npm install webpack-extension-reloader --save-dev`.
- [ ] Configure the Webpack development build to include the extension reloader.
- [ ] Update the Webpack configuration to use the reloader plugin.
- [ ] Ensure that the reloader is only active in development mode.
- [ ] Test the extension with the reloader to confirm that automatic reloading works as expected during development.
- [ ] Document the usage of the reloader package in our project's README or documentation.

### Labels:
- Enhancement
- Webpack
