### ISSUE TITLE
Add advanced hotkey functionality and anonymous feedback form

### ISSUE THREAD

**Issue by joseph-w-valdez** [alexjraymond/DuelingBookEnhanced#7]
### Description:
Add in some requested advanced hotkey functionality as well as an anonymous form to submit bugs and feedback. 

### Tasks:
- [x] Add function to track if the "Like Button" hotkey has been held down to change its functionality
- [x] Make SS Def hotkey
- [x] Make Detach hotkey
- [x] Make Overlay hotkey
- [x] Make OL ATK hotkey
- [x] Make OL DEF hotkey
- [x] Adjust the responsiveness of the Advanced page in the options so that it conditionally renders cards only to fit the screen
- [x] Add "Disable Hotkeys" option
~~- [ ] Add anonymous submission form for bugs and feedback to send us an email~~

### Labels:
- Enhancement

**Comment by joseph-w-valdez** [comment]
Cannot implement an anonymous form without setting up a backend server or AWS Lambda function. Will save this for a later version number, if at all.
