### ISSUE TITLE
Adding extra requested hotkeys

### ISSUE THREAD

**Issue by joseph-w-valdez** [alexjraymond/DuelingBookEnhanced#8]
### Description:
Adding in requested extra hotkeys related to the extra deck. 

### Tasks:
- [x] Add `To Extra Deck` hotkey, coupled with the `To Hand` action
- [x] Add separate `To Extra Deck FU` hotkey
- [x] Change `thumbsUpRelease` from hold to toggle
- [x] Add `Target` hotkey
- [x] Add `View Banished Cards` Hotkey
- [x] Fix bug with `Keep Going` / `Thumbs Up` being accessible while typing in a chat box
- [x] Add `Banish T.`  hotkey
- [x] Add `Enter` to `validHotkeys.ts` to make sure it shows up properly in the config
- [x] Add `Close View Menu` and edit `Toggle Chat Box` in config hotkeys but not let them be editable
- [x] Add in note in config hotkeys to let users know that they can tap the `View` hotkeys a second time to close them
- [x] Remove various buggy hotkeys such as `Tab` `Shift` `Ctrl` 
- [x] Investigate the `Mill X` actions being buggy with it saying `/Mill X` in chat but not sending the message
- [x] Push notifications for version updates
- [x] Disable or allow user to toggle `Hrm` messages with the `Thinking` hotkey 

### Labels:
- Enhancement
